// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAVKNBSYhLwZIL5SipNzHRrIZk5PKhU38',
    appId: '1:302966578842:web:2fcf2c74f0264051c20923',
    messagingSenderId: '302966578842',
    projectId: 'flutter-chat-app-ed532',
    authDomain: 'flutter-chat-app-ed532.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ed532.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMaTpDRnk0Gm3p0M7F8RwUeq8YV1IOqU',
    appId: '1:302966578842:android:64088409acee60fac20923',
    messagingSenderId: '302966578842',
    projectId: 'flutter-chat-app-ed532',
    storageBucket: 'flutter-chat-app-ed532.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrXoGWZaHYkVqQ1zTGGdunbc2zy1aIAQ',
    appId: '1:302966578842:ios:6996c60da975a18ec20923',
    messagingSenderId: '302966578842',
    projectId: 'flutter-chat-app-ed532',
    storageBucket: 'flutter-chat-app-ed532.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrXoGWZaHYkVqQ1zTGGdunbc2zy1aIAQ',
    appId: '1:302966578842:ios:6996c60da975a18ec20923',
    messagingSenderId: '302966578842',
    projectId: 'flutter-chat-app-ed532',
    storageBucket: 'flutter-chat-app-ed532.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAVKNBSYhLwZIL5SipNzHRrIZk5PKhU38',
    appId: '1:302966578842:web:79de1dbed1fc0306c20923',
    messagingSenderId: '302966578842',
    projectId: 'flutter-chat-app-ed532',
    authDomain: 'flutter-chat-app-ed532.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ed532.firebasestorage.app',
  );
}
